version: '3.8'
services:
  app:
    container_name: app
    working_dir: /app
    image: node:16-alpine
    volumes:
      - $PWD:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000